### PR TITLE
Issue 22: Controller describe-stream command bug

### LINKED ISSUE #22: controller describe-stream <scope-name> <stream-name> is throwing InterruptedException
Pravega-cli is giving error rather than correct output for the command:
` controller describe-stream <scope-name> <stream-name>`
```
> controller describe-stream longevity mediumScale
ERROR [2019-05-06 10:50:25.950] [Curator-Framework-0] o.a.c.f.imps.CuratorFrameworkImpl: Background exception was not retry-able or retry gave up
java.lang.InterruptedException: null
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1499)
        at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1487)
        at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1904)
        at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1937)
        at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:274)
        at org.apache.curator.framework.imps.CreateBuilderImpl$9.performBackgroundOperation(CreateBuilderImpl.java:799)
        at org.apache.curator.framework.imps.OperationAndData.callPerformBackgroundOperation(OperationAndData.java:84)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:947)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:925)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:73)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:322)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Exception accessing the metadata store: java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$DataNotFoundException: /store/longevity/mediumScale/configuration
```
Build details are:
```
Pravega version: 0.5.0-2236.5228e2d
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**  
Added support for Segment Tables metadata backend for describe-stream command.

**Purpose of the change**  
Fixes #22.

**What the code does**  
Pravega has recently changed the default storage metadata backend from Zookeeper to the Segment Store (Segment Tables). In this sense, the Pravega CLI `describe-stream` command requires access to the metadata backend, which was by default configured to be Zookeeper. This naturally prevents `describe-stream` command to work if the correct metadata backend is not configured.

This PR basically adds an additional parameter to the Pravega CLI (`cli.metadataBackend=segmentstore`) to choose the right metadata backend for the targeted Pravega cluster. Moreover, we also added the code to instantiate a `StreamMetadataStore` that queries the underlying Segment Tables.

Note that the current implementation of `describe-stream` is temporal, as it will be replaced by a REST API call to the Controller as the rest of Controller-related commands, thus simplifying the implementation of the command itself (see https://github.com/pravega/pravega/issues/3821).

**How to verify it**  
Tested `describe-stream` command with standalone and a pseudo distributed cluster and it worked. Also tested in a PKS cluster and it works too:
```
> controller describe-stream testAutoScale1737810171 testTxnScaleUpWithRead
Stream configuration: StreamConfiguration(scalingPolicy=ScalingPolicy(scaleType=BY_RATE_IN_EVENTS_PER_SEC, targetRate=1, scaleFactor=2, minNumSegments=2), retentionPolicy=null)
Stream state: ACTIVE
Total number of Stream segments: 21
Is Stream sealed? false
Current Stream epoch: 8, creation time: 1558109585955
Segments in active epoch:
> StreamSegmentRecord(segmentNumber=4, creationEpoch=6, creationTime=1558109141450, keyStart=0.0, keyEnd=0.25)
> StreamSegmentRecord(segmentNumber=7, creationEpoch=8, creationTime=1558109585955, keyStart=0.25, keyEnd=1.0)
Active Transactions in Stream:
Stream truncation record: lower epoch: -2147483648, high epoch: -2147483648, deleted segments: 0, StreamCut: {}
> Scale time: 1558109013842, splits: 0, merges: 0, segments: {0-1}
```

### CODE REVIEW

File: pravega-cli/src/main/java/io/pravega/tools/pravegacli/commands/controller/ControllerDescribeStreamCommand.java [hunk 1]
```diff
@@ -113,4 +145,20 @@ public static CommandDescriptor descriptor() {
                 new ArgDescriptor("scope-name", "Name of the Scope where the Stream belongs to."),
                 new ArgDescriptor("stream-name", "Name of the Stream to describe."));
     }
+
+    private SegmentHelper instantiateSegmentHelper(CuratorFramework zkClient) {
```
Comment (adrianmo) [inline pravega-cli/src/main/java/io/pravega/tools/pravegacli/commands/controller/ControllerDescribeStreamCommand.java:149]: Could this function be reused in the future by other commands? If yes, maybe this could be placed in some kind of helper class.

**Review by adrianmo — COMMENTED** [review]
The changes look good. I just have a comment, but maybe it's not important if this implementation is temporary.

File: pravega-cli/src/main/java/io/pravega/tools/pravegacli/commands/controller/ControllerDescribeStreamCommand.java (hunk 1 above)
Comment (RaulGracia) [reply pravega-cli/src/main/java/io/pravega/tools/pravegacli/commands/controller/ControllerDescribeStreamCommand.java:149]: Actually, the idea is to remove this by replacing the logic in this command by a REST API call as for the other Controller commands: https://github.com/pravega/pravega/issues/3821

**Review by adrianmo — APPROVED** [review]

**Comment by RaulGracia** [comment]
Please @Richa-Srivastava, can you test this branch before we merge?

**Comment by RaulGracia** [comment]
@Richa-Srivastava please, try again testing the command in PKS with the instructions I have given in #30. The command does work with a recent version of `master` and the proper Pravega CLI config. And please, post the result here in the PR (do not open a new issue for that).
